{% set version = "0.1.4" %}

package:
  name: rfc3339-validator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rfc3339-validator/rfc3339_validator-{{ version }}.tar.gz
  sha256: 138a2abdf93304ad60530167e51d2dfb9549521a836871b88d7f4695d0022f6b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python
    - six

test:
  source_files:
    - tests
  imports:
    - rfc3339_validator
  commands:
    - pip check
    - pytest
  requires:
    - hypothesis
    - pip
    - pytest-runner
    - strict-rfc3339

about:
  home: https://github.com/naimetti/rfc3339-validator
  summary: A pure python RFC3339 validator
  description: A pure python RFC3339 validator
  license_family: MIT
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/naimetti/rfc3339-validator/blob/master/README.md
  dev_url: https://github.com/naimetti/rfc3339-validator

extra:
  recipe-maintainers:
    - bollwyvl
